version: 0.2
env:
  variables:
    TF_VERSION: "1.0.6"
phases:
  install:
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip
      - curl -L -o opa https://openpolicyagent.org/downloads/v0.32.0/opa_linux_amd64_static
      - chmod 755 ./opa
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -no-color
      - terraform plan -out tf.plan
      - terraform show -json tf.plan > tf.json
      - opa eval --format pretty --data ./test/opa/terraform.rego --input tf.json "data.terraform"
  post_build:
    commands:
      - echo "OPA Test completed on `date`"
